services:
  web:
    build: ./restaurant
    container_name: django
    volumes:
      - ./restaurant/:/usr/src/app/
    ports:
      - 8080:8000  # порт 8080 для хоста
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17.4
    restart: always
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5000:5432  # порт 5000 для хоста


  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 80:8080  # порт 80 для хоста


volumes:
  postgres_data: